---
version: '2'

services:
  sonarqube:
    container_name: sonarqube_web
    depends_on:
      - install_plugins
      - plugins
      - postgresql
    image: sonarqube:6.0-alpine
    ports:
     - "9000:9000"
    links:
      - postgresql:db
    env_file:
      - ./env/web.env
      - ./env/web.secrets.env
    volumes_from:
     - plugins
    restart: always 

  plugins:
    container_name: sonarqube_plugins
    image: sonarqube:6.0-alpine
    volumes:
     - /opt/sonarqube/extensions
     - /opt/sonarqube/lib/bundled-plugins
    command: /bin/true

  install_plugins:
    container_name: sonarqube_install_plugins
    build: plugins
    volumes_from:
     - plugins
    restart: never

  postgresql:
    container_name: sonarqube_db
    image: orchardup/postgresql:latest
    env_file:
      - ./env/db.env
      - ./env/db.secrets.env
    volumes:
      - ./sonarqube/data:/var/lib/postgresql
    ports:
      - "5432:5432"

  ssl_proxy:
    container_name: sonarqube_ssl_proxy
    image: eu.gcr.io/windy-oxide-102215/nginx-proxy:latest
    depends_on:
      - sonarqube
    links:
      - sonarqube:sonarqube
    ports:
      - "80:80"
      - "443:443"
      - "9113:9113"
    volumes:
      - ./ssl:/ssl
    env_file:
      - ./env/ssl_proxy.env
